# Generated by Django 5.1.4 on 2025-04-10 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cours',
            name='volumehoraire',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
