# Generated by Django 5.1.4 on 2025-04-12 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_alter_cours_volumehoraire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cours',
            name='anneeetude',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('etudiant', 'Étudiant'), ('secretaire', 'Secrétaire'), ('enseignant', 'Enseignant')], default='secretaire', max_length=20),
        ),
    ]
