# Generated by Django 5.1.4 on 2025-04-23 10:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_alter_cours_anneeetude_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='cours',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='gestion.cours'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='etudiant',
            field=models.ForeignKey(limit_choices_to={'role': 'etudiant'}, on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='inscription',
            unique_together={('etudiant', 'cours')},
        ),
        migrations.AddConstraint(
            model_name='inscription',
            constraint=models.UniqueConstraint(fields=('etudiant', 'cours'), name='unique_inscription'),
        ),
    ]
