# Generated by Django 5.1.4 on 2025-04-23 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_alter_inscription_cours_alter_inscription_etudiant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
