# Generated by Django 5.1.4 on 2025-04-09 17:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nom', models.CharField(blank=True, max_length=100, null=True)),
                ('prenom', models.CharField(blank=True, max_length=100, null=True)),
                ('tel', models.CharField(blank=True, max_length=20, null=True)),
                ('role', models.CharField(choices=[('etudiant', 'Étudiant'), ('secretaire', 'Secrétaire'), ('enseignant', 'Enseignant')], default='etudiant', max_length=20)),
                ('anneeinscrit', models.CharField(blank=True, max_length=4, null=True)),
                ('fonction', models.CharField(blank=True, max_length=50, null=True)),
                ('filiere', models.CharField(blank=True, max_length=50, null=True)),
                ('anneeetude', models.CharField(blank=True, max_length=4, null=True)),
                ('datedenaissance', models.DateField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='custom_user_set', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='custom_user_permissions_set', to='auth.permission')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('volumehoraire', models.IntegerField()),
                ('type_cours', models.CharField(max_length=20)),
                ('semestre', models.CharField(max_length=10)),
                ('anneeetude', models.CharField(max_length=4)),
                ('enseignant', models.ForeignKey(limit_choices_to={'role': 'enseignant'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Exercice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('titre_exercice', models.CharField(max_length=50)),
                ('date_limite', models.DateTimeField()),
                ('type_exercice', models.CharField(max_length=20)),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.cours')),
            ],
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.cours')),
                ('etudiant', models.ForeignKey(limit_choices_to={'role': 'etudiant'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_examen', models.CharField(max_length=20)),
                ('note', models.DecimalField(decimal_places=2, max_digits=4)),
                ('explication', models.TextField()),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.cours')),
                ('etudiant', models.ForeignKey(limit_choices_to={'role': 'etudiant'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Seance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duree', models.IntegerField()),
                ('date', models.DateField()),
                ('heure_debut', models.TimeField()),
                ('salle', models.CharField(max_length=10)),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.cours')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('etudiant', models.ForeignKey(limit_choices_to={'role': 'etudiant'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('seance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.seance')),
            ],
        ),
        migrations.CreateModel(
            name='SoumissionExercice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='soumissions/')),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('etudiant', models.ForeignKey(limit_choices_to={'role': 'etudiant'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('exercice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.exercice')),
            ],
        ),
    ]
